name: makatib
description: تطبيق مكاتب - شاشة افتتاحية
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/onboarding/
    - assets/units/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/logo.png
  web: false
